import type {Metadata} from 'next';
import {Montserrat, Open_Sans} from 'next/font/google';
import './globals.css';
import {Toaster} from "@/components/ui/toaster";

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
});

const openSans = Open_Sans({
  subsets: ['latin'],
  variable: '--font-open-sans',
});

export const metadata: Metadata = {
  title: 'LoveLink Family App',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${montserrat.variable} ${openSans.variable} antialiased`}>
        {children}
        <Toaster/>
      </body>
    </html>
  );
}
